### ISSUE TITLE
Feature request: Be able to offload to Intel

### ISSUE THREAD

**Issue by Raviu56** [openSUSE/SUSEPrime#95]
Thanks so much for this gem tool.

Here is my `inxi -G` output
```
Graphics:
  Device-1: Intel Alder Lake-P GT1 [UHD Graphics] driver: i915 v: kernel
  Device-2: NVIDIA GA107M [GeForce RTX 3050 Mobile] driver: nvidia
    v: 525.89.02
  Display: x11 server: X.Org v: 21.1.7 with: Xwayland v: 23.1.0 driver: X:
    loaded: modesetting,nvidia dri: iris gpu: i915 resolution: 1920x1080~120Hz
  API: OpenGL v: 4.6.0 NVIDIA 525.89.02 renderer: NVIDIA GeForce RTX 3050
    Laptop GPU/PCIe/SSE2
 ```
 
 I'm using prime-select to use nvidia . I know about the current offload mode which allows me to run Intel and offload some programs to nvidia. I need the vise versa, run on nvidia and be able to offload some programs to intel graphics.
 
 I've some use-cases where this could be very useful for me, one of them running 3D accelerated VMs on Intel card  when I'm having busy nvidia card.
